name: streamlit_sia
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip=23.1.2
  - pip:
      - streamlit==1.29.0
      - pandas==2.0.3
      - openai==0.27.0
      - langchain==0.0.141
      - huggingface-hub==0.11.0
      - matplotlib==3.5.1
